name: solana_wallet_adpater_example
description: An example app for solana_wallet_adapter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Add latest packages.
  solana_web3: ^0.1.1
  solana_wallet_adapter: ^0.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
